# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(595, 529)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_escolher_arquivo = QtWidgets.QPushButton(self.centralwidget)
        self.btn_escolher_arquivo.setObjectName("btn_escolher_arquivo")
        self.gridLayout.addWidget(self.btn_escolher_arquivo, 1, 5, 1, 1)
        self.btn_redimensionar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_redimensionar.setObjectName("btn_redimensionar")
        self.gridLayout.addWidget(self.btn_redimensionar, 3, 5, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 575, 422))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_IMG = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_IMG.setText("")
        self.label_IMG.setObjectName("label_IMG")
        self.gridLayout_2.addWidget(self.label_IMG, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 6)
        self.input_largura = QtWidgets.QLineEdit(self.centralwidget)
        self.input_largura.setObjectName("input_largura")
        self.gridLayout.addWidget(self.input_largura, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.btn_salvar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_salvar.setObjectName("btn_salvar")
        self.gridLayout.addWidget(self.btn_salvar, 4, 5, 1, 1)
        self.input_arquivo = QtWidgets.QLineEdit(self.centralwidget)
        self.input_arquivo.setObjectName("input_arquivo")
        self.gridLayout.addWidget(self.input_arquivo, 1, 0, 1, 5)
        self.input_altura = QtWidgets.QLineEdit(self.centralwidget)
        self.input_altura.setObjectName("input_altura")
        self.gridLayout.addWidget(self.input_altura, 3, 3, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Redimensionar Imagem"))
        self.btn_escolher_arquivo.setText(_translate("MainWindow", "Abrir Foto"))
        self.btn_redimensionar.setText(_translate("MainWindow", "Redimensionar"))
        self.label_2.setText(_translate("MainWindow", "Altura"))
        self.label.setText(_translate("MainWindow", "Largura"))
        self.btn_salvar.setText(_translate("MainWindow", "Salvar"))
