# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(554, 141)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.input_valida_cpf = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.input_valida_cpf.setFont(font)
        self.input_valida_cpf.setObjectName("input_valida_cpf")
        self.gridLayout.addWidget(self.input_valida_cpf, 0, 1, 1, 1)
        self.btn_valida_cpf = QtWidgets.QPushButton(self.centralwidget)
        self.btn_valida_cpf.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.btn_valida_cpf.setFont(font)
        self.btn_valida_cpf.setObjectName("btn_valida_cpf")
        self.gridLayout.addWidget(self.btn_valida_cpf, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.btn_gera_cpf = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.btn_gera_cpf.setFont(font)
        self.btn_gera_cpf.setObjectName("btn_gera_cpf")
        self.gridLayout.addWidget(self.btn_gera_cpf, 1, 2, 1, 1)
        self.label_retorno = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(18)
        self.label_retorno.setFont(font)
        self.label_retorno.setStyleSheet("color: green")
        self.label_retorno.setText("")
        self.label_retorno.setAlignment(QtCore.Qt.AlignCenter)
        self.label_retorno.setObjectName("label_retorno")
        self.gridLayout.addWidget(self.label_retorno, 2, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Validador e Gerador de CPF"))
        self.label.setText(_translate("MainWindow", "Validar CPF:"))
        self.btn_valida_cpf.setText(_translate("MainWindow", "Validar CPF"))
        self.label_2.setText(_translate("MainWindow", "Gera CPF:"))
        self.btn_gera_cpf.setText(_translate("MainWindow", "Gerar CPF"))
